kvepalu_katalogas = {
    f"Prekė-{i:02}": {"pavad.": p["pavadinimas"], "kaina": p["kaina"], "likutis": 10}
    for i, p in enumerate([
        {"pavadinimas": "Amouage Interlude Man", "kaina": 250},
        {"pavadinimas": "Creed Aventus", "kaina": 320},
        {"pavadinimas": "Maison Francis Kurkdjian Baccarat Rouge 540", "kaina": 300},
        {"pavadinimas": "Tom Ford Tobacco Vanille", "kaina": 270},
        {"pavadinimas": "Byredo Gypsy Water", "kaina": 190},
        {"pavadinimas": "Le Labo Santal 33", "kaina": 220},
        {"pavadinimas": "Diptyque Philosykos", "kaina": 150},
        {"pavadinimas": "Jo Malone Wood Sage & Sea Salt", "kaina": 140},
        {"pavadinimas": "Parfums de Marly Layton", "kaina": 260},
        {"pavadinimas": "Initio Parfums Oud for Greatness", "kaina": 330},
        {"pavadinimas": "Xerjoff Naxos", "kaina": 290},
        {"pavadinimas": "Nasomatto Black Afgano", "kaina": 210},
        {"pavadinimas": "Mancera Cedrat Boise", "kaina": 120},
        {"pavadinimas": "Montale Intense Cafe", "kaina": 130},
        {"pavadinimas": "Escentric Molecules Molecule 01", "kaina": 100},
        {"pavadinimas": "Juliette Has a Gun Not a Perfume", "kaina": 135},
        {"pavadinimas": "Frederic Malle Portrait of a Lady", "kaina": 280},
        {"pavadinimas": "Serge Lutens Chergui", "kaina": 150},
        {"pavadinimas": "Maison Margiela Replica Jazz Club", "kaina": 120},
        {"pavadinimas": "Penhaligon's Halfeti", "kaina": 200},
        {"pavadinimas": "Clive Christian No. 1", "kaina": 650},
        {"pavadinimas": "Roja Parfums Elysium", "kaina": 350},
        {"pavadinimas": "Bond No. 9 New York Oud", "kaina": 320},
        {"pavadinimas": "Acqua di Parma Colonia", "kaina": 180},
        {"pavadinimas": "Hermès Terre d'Hermès", "kaina": 110},
        {"pavadinimas": "Guerlain Santal Royal", "kaina": 220},
        {"pavadinimas": "Yves Saint Laurent Tuxedo", "kaina": 240},
        {"pavadinimas": "Chanel Les Exclusifs de Chanel Sycomore", "kaina": 300},
        {"pavadinimas": "Dior Ambre Nuit", "kaina": 290},
        {"pavadinimas": "Giorgio Armani Privé Oud Royal", "kaina": 350},
        {"pavadinimas": "Kilian Black Phantom", "kaina": 270},
        {"pavadinimas": "Lalique Encre Noire", "kaina": 90},
        {"pavadinimas": "Amouage Jubilation XXV", "kaina": 250},
        {"pavadinimas": "Creed Green Irish Tweed", "kaina": 310},
        {"pavadinimas": "Tom Ford Noir de Noir", "kaina": 260},
        {"pavadinimas": "Byredo Bal d'Afrique", "kaina": 200},
        {"pavadinimas": "Le Labo Bergamote 22", "kaina": 230},
        {"pavadinimas": "Diptyque Eau Duelle", "kaina": 140},
        {"pavadinimas": "Jo Malone Peony & Blush Suede", "kaina": 150},
        {"pavadinimas": "Parfums de Marly Herod", "kaina": 280},
        {"pavadinimas": "Initio Parfums Rehab", "kaina": 310},
        {"pavadinimas": "Xerjoff Erba Pura", "kaina": 320},
        {"pavadinimas": "Nasomatto Baraonda", "kaina": 220},
        {"pavadinimas": "Mancera Roses Vanille", "kaina": 130},
        {"pavadinimas": "Montale Dark Purple", "kaina": 150},
        {"pavadinimas": "Escentric Molecules Molecule 02", "kaina": 100},
        {"pavadinimas": "Juliette Has a Gun Vanilla Vibes", "kaina": 140},
        {"pavadinimas": "Frederic Malle Musc Ravageur", "kaina": 280},
        {"pavadinimas": "Serge Lutens Ambre Sultan", "kaina": 170},
{"pavadinimas": "Maison Margiela Replica By the Fireplace", "kaina": 120},
    ], start=1)
}

